import uuid
import datetime

# Step 2 from the README. 
# The empty structure that will hold transactions.
transactions = []

# Step 3
# Function that allows deposits(add_deposit)
# Algorithm. 
   # def the add_deposit function. Its parameter will be  amount.  ID, type, and date will be generated by the function
   # Append deposit to transactions as a dictionary containing the amount, ID, type, and date.


   

def add_deposit(amount):

    my_dict = {
    "id": uuid.uuid4(),
    "amount": amount,
    "type": "deposit",
    "date": datetime.datetime.now()
}
    transactions.append(my_dict)


#add_deposit(500)
#add_deposit(15000)
add_deposit(350000)
print(transactions)