import uuid
import datetime

# Step 2 from the README. 
# The empty structure that will hold transactions.
transactions = []

# Step 3
# Function that allows deposits(add_deposit)
# Algorithm. 
   # def the add_deposit function. Its parameter will be  amount.  ID, type, and date will be generated by the function
   # Append deposit to transactions as a dictionary containing the amount, ID, type, and date.


   

def add_deposit(amount):

    fields = {
    "id": uuid.uuid4(),
    "amount": amount,
    "type": "deposit",
    "date": datetime.datetime.now()
}
    transactions.append(fields)


add_deposit(500)
add_deposit(15000)
add_deposit(350000)
#print(transactions)

# Step 4 
# Function that checks the available balance
# Loops through the ledger(transactions) and computes net balance
# Algorithm
    # define a function 'check_balance'. It doesn't take in any parameter.
    # initialize a variable available_balance that stores the initial account's net balance. Initialize it to 0 since no transaction has happened at this stage. We have an empty ledger
    # Loops through the list to check transaction type
    # If type is deposit, add deposit amount to available_balance
    # If type is withdrawal, substract withdrawal amount from available_balance
    # return the net balance
    # call check_balance


def check_balance():
    available_balance = 0

    for transaction in transactions:
        if transaction["type"] == 'deposit':
            available_balance += transaction["amount"]
        elif transaction["type"] == 'withdrawal':
            available_balance -= transaction["amount"]

    return available_balance
print(check_balance() )       
        
        